// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChDIyqrWqiPJH952AuepIWvaNhK6vECT8',
    appId: '1:1015769960470:web:66503c7b15928ae671e537',
    messagingSenderId: '1015769960470',
    projectId: 'scholar-ec7bd',
    authDomain: 'scholar-ec7bd.firebaseapp.com',
    storageBucket: 'scholar-ec7bd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNjyxeUGkFrnlLRqCKOtv7NTcjTiurpFE',
    appId: '1:1015769960470:android:588fa72bd0c725c871e537',
    messagingSenderId: '1015769960470',
    projectId: 'scholar-ec7bd',
    storageBucket: 'scholar-ec7bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8LldSS0Ly4o6jezF-NRzAbr6yrACNMUY',
    appId: '1:1015769960470:ios:ace34200aaa5fd5071e537',
    messagingSenderId: '1015769960470',
    projectId: 'scholar-ec7bd',
    storageBucket: 'scholar-ec7bd.appspot.com',
    iosBundleId: 'com.example.parentTeacherFeedbackApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8LldSS0Ly4o6jezF-NRzAbr6yrACNMUY',
    appId: '1:1015769960470:ios:e3d1936f810e26eb71e537',
    messagingSenderId: '1015769960470',
    projectId: 'scholar-ec7bd',
    storageBucket: 'scholar-ec7bd.appspot.com',
    iosBundleId: 'com.example.parentTeacherFeedbackApp.RunnerTests',
  );
}
